### ISSUE TITLE
Write TC submission

### ISSUE THREAD

**Issue by ncovercash** [ualibweb/ua-folio-docs#4]
[link](https://github.com/ualibweb/ua-folio-docs/tree/main/docs/mod-calendar-2.0-tech-council/evaluation-forms)

**Comment by sjturner-ua** [comment]
Great, and thank you.

**Comment by ncovercash** [comment]
Meant to send this earlier; [here](https://github.com/ualibweb/ua-folio-docs/tree/main/docs/mod-calendar-2.0-tech-council/evaluation-forms) are the evaluation forms.  You should be able to edit them via the GitHub interface (or you can send any needed changes my way).  Let me know if you have any questions, I am currently working through the self-evaluations

**Comment by ncovercash** [comment]
Finished the forms for mod-calendar, with the exception of re-verifying and writing Karate tests, which I will complete tomorrow.  Every other criteria is either met or inapplicable (sonarcloud reported a number of false positives, but no real issues)

**Comment by ncovercash** [comment]
Completed writing new Karate tests

**Comment by sjturner-ua** [comment]
Thanks Noah.
